### ISSUE TITLE
Filenames of exactly 26 characters get scrambled

### ISSUE THREAD

**Issue by rasa** [mitchellh/go-fs#1]
I'm using packer to build a floppy with a file named `enable-quick-edit-mode.cmd`. The resultant floppy image's filename appears corrupted in Windows (under VMWare), in IsoBuster, and when I mount the image using ImDisk Virtual Disk Driver for Windows.

When I rename the file to be 25 or 27 characters, the corruption disappears. 

Here's a screenshot of the corruption in IsoBuster:
![screenshot - 11_14_13 11_04_56 am](https://f.cloud.github.com/assets/220772/1543980/49980edc-4d60-11e3-9217-1565def35714.png)

Here's another screenshot that shows only files of exactly 26 characters are affected:
![screenshot - 11_14_13 2_34_14 pm](https://f.cloud.github.com/assets/220772/1545900/fc397122-4d7c-11e3-8d26-8d3f1272c45e.png)

**Comment by mitchellh** [comment]
Oof thanks. I'll take a look at this.

**Comment by rasa** [comment]
I'm happy to look into it as well, if you'd like. Just assign it to me, if you can.
