### ISSUE TITLE
super_floppy doesn't create a proper 1.44 MB floppy image understood by old OS'es

### ISSUE THREAD

**Issue by mrdima** [mitchellh/go-fs#11]
Older OS'es (at least Windows 2000/XP/2003) don't understand the floppy image created, at least during the boot sequence. For modern OS'es or sometimes when old OS'es are booted fully it's not a problem, but it creates an issue for creating unattended setups of these older OS'es using packer.
This is the same issue as referenced in packer 2421; https://github.com/mitchellh/packer/issues/2421

**Comment by Xyon** [comment]
I've incorporated this PR into my own packer install and it solved my Windows XP headaches. Thanks very much for the solution - hope you get merged in soon, so I can stop using a cobbled-together copy of Packer!
